In [129]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [130]:
df= pd.read_csv(r'C:\Users\16479\Downloads\Group Project Data-SFD Data-Toronto Police.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5707 entries, 0 to 5706
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   X                  5707 non-null   float64
 1   Y                  5707 non-null   float64
 2   OBJECTID           5707 non-null   int64
 3   EVENT_UNIQUE_ID    5707 non-null   object
 4   OCC_DATE           5707 non-null   object
 5   OCC_YEAR           5707 non-null   int64
 6   OCC_MONTH          5707 non-null   object
 7   OCC_DOW            5707 non-null   object
 8   OCC_DOY            5707 non-null   int64
 9   OCC_DAY            5707 non-null   int64
 10  OCC_HOUR           5707 non-null   int64
 11  OCC_TIME_RANGE     5707 non-null   object
 12  DIVISION           5707 non-null   object
 13  DEATH              5707 non-null   int64
 14  INJURIES           5707 non-null   int64
 15  HOOD_158           5707 non-null   object
 16  NEIGHBOURHOOD_158  5707 non-null   object
 17  HOOD_140           5707 non-null   object
 18  NEIGHBOURHOOD_140  5707 non-null   object
 19  LONG_WGS84         5707 non-null   float64
 20  LAT_WGS84          5707 non-null   float64
dtypes: float64(4), int64(7), object(10)
memory usage: 936.4+ KB

In [131]:
df.head(5)

,X,Y,OBJECTID,EVENT_UNIQUE_ID,OCC_DATE,OCC_YEAR,OCC_MONTH,OCC_DOW,OCC_DOY,OCC_DAY,...,OCC_TIME_RANGE,DIVISION,DEATH,INJURIES,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84
0,-79.234955,43.781528,1,GO-2004397105,2004/05/15 04:00:00+00,2004,May,Saturday,136,15,...,Night,D41,0,0,142,Woburn North,137,Woburn (137),-79.234955,43.781528
1,-79.618218,43.733547,2,GO-2004600109,2004/07/26 04:00:00+00,2004,July,Monday,208,26,...,Evening,D23,0,0,1,West Humber-Clairville,1,West Humber-Clairville (1),-79.618218,43.733547
2,-79.518759,43.769157,3,GO-2004311851,2004/05/14 04:00:00+00,2004,May,Friday,135,14,...,Afternoon,D31,1,1,24,Black Creek,24,Black Creek (24),-79.518759,43.769157
3,-79.378870,43.660665,4,GO-2004736004,2004/12/19 05:00:00+00,2004,December,Sunday,354,19,...,Night,D51,1,0,168,Downtown Yonge East,75,Church-Yonge Corridor (75),-79.378870,43.660665
4,-79.212435,43.812075,5,GO-2004303455,2004/04/12 04:00:00+00,2004,April,Monday,103,12,...,Evening,D42,0,0,146,Malvern East,132,Malvern (132),-79.212435,43.812075

In [132]:
wt= pd.read_csv(r'C:\Users\16479\Downloads\weatherstats_toronto_daily.csv')

C:\Users\16479\AppData\Local\Temp\ipykernel_31360\3232824098.py:1: DtypeWarning: Columns (46,49) have mixed types. Specify dtype option on import or set low_memory=False.
  wt= pd.read_csv(r'C:\Users\16479\Downloads\weatherstats_toronto_daily.csv')

In [133]:
wt['date'] = pd.to_datetime(wt['date'])  # Convert date column to datetime if needed

# Filter rows based on the date range
start_date = pd.to_datetime('2004-01-01')
end_date = pd.to_datetime('2022-12-31')
filtered_wt = wt[(wt['date'] >= start_date) & (wt['date'] <= end_date)]

In [134]:
wt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31306 entries, 0 to 31305
Data columns (total 72 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           31306 non-null  datetime64[ns]
 1   max_temperature                31176 non-null  float64
 2   avg_hourly_temperature         25765 non-null  float64
 3   avg_temperature                31167 non-null  float64
 4   min_temperature                31170 non-null  float64
 5   max_humidex                    6743 non-null   float64
 6   min_windchill                  9574 non-null   float64
 7   max_relative_humidity          25765 non-null  float64
 8   avg_hourly_relative_humidity   25765 non-null  float64
 9   avg_relative_humidity          25765 non-null  float64
 10  min_relative_humidity          25765 non-null  float64
 11  max_dew_point                  25765 non-null  float64
 12  avg_hourly_dew_point           25765 non-null  float64
 13  avg_dew_point                  25765 non-null  float64
 14  min_dew_point                  25765 non-null  float64
 15  max_wind_speed                 25765 non-null  float64
 16  avg_hourly_wind_speed          25765 non-null  float64
 17  avg_wind_speed                 25765 non-null  float64
 18  min_wind_speed                 25765 non-null  float64
 19  max_wind_gust                  17208 non-null  float64
 20  wind_gust_dir_10s              17207 non-null  float64
 21  max_pressure_sea               25765 non-null  float64
 22  avg_hourly_pressure_sea        25765 non-null  float64
 23  avg_pressure_sea               25765 non-null  float64
 24  min_pressure_sea               25765 non-null  float64
 25  max_pressure_station           25765 non-null  float64
 26  avg_hourly_pressure_station    25765 non-null  float64
 27  avg_pressure_station           25765 non-null  float64
 28  min_pressure_station           25765 non-null  float64
 29  max_visibility                 25765 non-null  float64
 30  avg_hourly_visibility          25765 non-null  float64
 31  avg_visibility                 25765 non-null  float64
 32  min_visibility                 25765 non-null  float64
 33  max_health_index               240 non-null    float64
 34  avg_hourly_health_index        240 non-null    float64
 35  avg_health_index               240 non-null    float64
 36  min_health_index               240 non-null    float64
 37  heatdegdays                    31167 non-null  float64
 38  cooldegdays                    31167 non-null  float64
 39  growdegdays_5                  31167 non-null  float64
 40  growdegdays_7                  31167 non-null  float64
 41  growdegdays_10                 31167 non-null  float64
 42  precipitation                  31097 non-null  float64
 43  rain                           31087 non-null  float64
 44  snow                           31097 non-null  float64
 45  snow_on_ground                 22250 non-null  float64
 46  sunrise_hhmm                   3485 non-null   object
 47  sunrise_unixtime               3485 non-null   float64
 48  sunrise_f                      3485 non-null   float64
 49  sunset_hhmm                    3485 non-null   object
 50  sunset_unixtime                3485 non-null   float64
 51  sunset_f                       3485 non-null   float64
 52  daylight                       3485 non-null   float64
 53  min_uv_forecast                2836 non-null   float64
 54  max_uv_forecast                2836 non-null   float64
 55  min_high_temperature_forecast  3485 non-null   float64
 56  max_high_temperature_forecast  3485 non-null   float64
 57  min_low_temperature_forecast   3485 non-null   float64
 58  max_low_temperature_forecast   3485 non-null   float64
 59  solar_radiation                0 non-null      float64
 60  max_cloud_cover_4              0 non-null      float64
 61  avg_hourly_cloud_cover_4       0 non-null      float64
 62  avg_cloud_cover_4              0 non-null      float64
 63  min_cloud_cover_4              0 non-null      float64
 64  max_cloud_cover_8              3569 non-null   float64
 65  avg_hourly_cloud_cover_8       3569 non-null   float64
 66  avg_cloud_cover_8              3569 non-null   float64
 67  min_cloud_cover_8              3569 non-null   float64
 68  max_cloud_cover_10             237 non-null    float64
 69  avg_hourly_cloud_cover_10      237 non-null    float64
 70  avg_cloud_cover_10             237 non-null    float64
 71  min_cloud_cover_10             237 non-null    float64
dtypes: datetime64[ns](1), float64(69), object(2)
memory usage: 17.2+ MB

In [135]:
desired_columns = [col for col in wt.columns if col.startswith('avg') and 'hourly' not in col]
desired_columns += ['date','snow', 'precipitation', 'rain']
filtered_wt = wt[desired_columns]

In [136]:
fields_to_remove = ['avg_health_index','avg_dew_point', 'avg_pressure_station', 'avg_pressure_sea', 'avg_cloud_cover_4', 'avg_cloud_cover_8', 'avg_cloud_cover_10', 'avg_dew_point']
filtered_wt = filtered_wt.drop(fields_to_remove, axis=1)

In [137]:
# Fill null values with forward fill strategy
filtered_wt['avg_temperature'].fillna(method='ffill', inplace=True)
filtered_wt['avg_relative_humidity'].fillna(method='ffill', inplace=True)
filtered_wt['avg_wind_speed'].fillna(method='ffill', inplace=True)
filtered_wt['avg_visibility'].fillna(method='ffill', inplace=True)
filtered_wt['snow'].fillna(method='ffill', inplace=True)
filtered_wt['precipitation'].fillna(method='ffill', inplace=True)
filtered_wt['rain'].fillna(method='ffill', inplace=True)

In [138]:
null_counts = filtered_wt.isnull().sum()
print(null_counts)

avg_temperature          0
avg_relative_humidity    0
avg_wind_speed           0
avg_visibility           0
date                     0
snow                     0
precipitation            0
rain                     0
dtype: int64

In [139]:
filtered_wt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31306 entries, 0 to 31305
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   avg_temperature        31306 non-null  float64
 1   avg_relative_humidity  31306 non-null  float64
 2   avg_wind_speed         31306 non-null  float64
 3   avg_visibility         31306 non-null  float64
 4   date                   31306 non-null  datetime64[ns]
 5   snow                   31306 non-null  float64
 6   precipitation          31306 non-null  float64
 7   rain                   31306 non-null  float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 1.9 MB

In [140]:
df['OCC_DATE'] = pd.to_datetime(df['OCC_DATE']).dt.date
filtered_wt['date'] = pd.to_datetime(filtered_wt['date']).dt.date

# Merge the datasets based on the common date column
merged_df = pd.merge(df, filtered_wt, left_on='OCC_DATE', right_on='date')

merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5707 entries, 0 to 5706
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   X                      5707 non-null   float64
 1   Y                      5707 non-null   float64
 2   OBJECTID               5707 non-null   int64
 3   EVENT_UNIQUE_ID        5707 non-null   object
 4   OCC_DATE               5707 non-null   object
 5   OCC_YEAR               5707 non-null   int64
 6   OCC_MONTH              5707 non-null   object
 7   OCC_DOW                5707 non-null   object
 8   OCC_DOY                5707 non-null   int64
 9   OCC_DAY                5707 non-null   int64
 10  OCC_HOUR               5707 non-null   int64
 11  OCC_TIME_RANGE         5707 non-null   object
 12  DIVISION               5707 non-null   object
 13  DEATH                  5707 non-null   int64
 14  INJURIES               5707 non-null   int64
 15  HOOD_158               5707 non-null   object
 16  NEIGHBOURHOOD_158      5707 non-null   object
 17  HOOD_140               5707 non-null   object
 18  NEIGHBOURHOOD_140      5707 non-null   object
 19  LONG_WGS84             5707 non-null   float64
 20  LAT_WGS84              5707 non-null   float64
 21  avg_temperature        5707 non-null   float64
 22  avg_relative_humidity  5707 non-null   float64
 23  avg_wind_speed         5707 non-null   float64
 24  avg_visibility         5707 non-null   float64
 25  date                   5707 non-null   object
 26  snow                   5707 non-null   float64
 27  precipitation          5707 non-null   float64
 28  rain                   5707 non-null   float64
dtypes: float64(11), int64(7), object(11)
memory usage: 1.3+ MB

In [141]:
merged_df.insert(merged_df.columns.get_loc('INJURIES') + 1, 'TOTAL_CASUALTIES', merged_df['DEATH'] + merged_df['INJURIES'])

In [142]:
correlation = merged_df[['avg_temperature', 'avg_wind_speed', 'avg_visibility', 'snow', 'precipitation', 'rain', 'TOTAL_CASUALTIES']].corr()
correlation

,avg_temperature,avg_wind_speed,avg_visibility,snow,precipitation,rain,TOTAL_CASUALTIES
avg_temperature,1.000000,-0.218661,0.225176,-0.243769,0.063862,0.113775,0.006397
avg_wind_speed,-0.218661,1.000000,-0.082607,0.081209,0.069806,0.051912,0.002519
avg_visibility,0.225176,-0.082607,1.000000,-0.289937,-0.418840,-0.370368,0.000279
snow,-0.243769,0.081209,-0.289937,1.000000,0.188428,-0.005778,-0.007483
precipitation,0.063862,0.069806,-0.418840,0.188428,1.000000,0.974982,-0.013357
rain,0.113775,0.051912,-0.370368,-0.005778,0.974982,1.000000,-0.012643
TOTAL_CASUALTIES,0.006397,0.002519,0.000279,-0.007483,-0.013357,-0.012643,1.000000

In [143]:
import statsmodels.api as sm

# Define the predictor variables (weather fields)
X = merged_df[['avg_temperature', 'avg_wind_speed', 'avg_visibility', 'snow', 'precipitation', 'rain']]

# Add a constant column to the predictor variables
X = sm.add_constant(X)

# Define the target variable (TOTAL_CASUALTIES)
y = merged_df['TOTAL_CASUALTIES']

# Fit the OLS model
model = sm.OLS(y, X)
results = model.fit()

# Print the summary of the regression results
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       TOTAL_CASUALTIES   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.3632
Date:                Wed, 19 Jul 2023   Prob (F-statistic):              0.902
Time:                        02:14:44   Log-Likelihood:                -7098.9
No. Observations:                5707   AIC:                         1.421e+04
Df Residuals:                    5700   BIC:                         1.426e+04
Df Model:                           6
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               0.6365      0.067      9.540      0.000       0.506       0.767
avg_temperature     0.0008      0.001      0.685      0.493      -0.001       0.003
avg_wind_speed      0.0007      0.002      0.391      0.696      -0.003       0.004
avg_visibility  -1.926e-06   2.78e-06     -0.692      0.489   -7.38e-06    3.53e-06
snow               -0.0111      0.020     -0.559      0.576      -0.050       0.028
precipitation       0.0052      0.018      0.283      0.777      -0.031       0.041
rain               -0.0080      0.019     -0.431      0.666      -0.045       0.028
==============================================================================
Omnibus:                     7644.878   Durbin-Watson:                   1.898
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          6519861.948
Skew:                           7.034   Prob(JB):                         0.00
Kurtosis:                     167.986   Cond. No.                     1.26e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [144]:
merged_df['OCC_DOW'].unique()

array(['Saturday', 'Monday', 'Friday', 'Sunday', 'Wednesday', 'Thursday',
       'Tuesday'], dtype=object)

In [145]:
merged_df['TOTAL_CASUALTIES'] = pd.to_numeric(merged_df['TOTAL_CASUALTIES'])

In [148]:
import statsmodels.api as sm

# Create new numerical fields based on 'OCC_TIME_RANGE' and 'OCC_DOW'
time_range_mapping = {
    'Night': 1,
    'Evening': 2,
    'Afternoon': 3,
    'Morning': 4
}

dow_mapping = {
    'Monday': 1,
    'Tuesday': 2,
    'Wednesday': 3,
    'Thursday': 4,
    'Friday': 5,
    'Saturday': 6,
    'Sunday': 7
}

merged_df['time_range_num'] = merged_df['OCC_TIME_RANGE'].map(time_range_mapping)
merged_df['dow_num'] = merged_df['OCC_DOW'].map(dow_mapping)

# Perform OLS regression
X = merged_df[['time_range_num', 'dow_num']]
X = sm.add_constant(X)  # Add a constant term to the model
y = merged_df['TOTAL_CASUALTIES']


model = sm.OLS(y, X)
results = model.fit()

# Print the summary of the regression results
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       TOTAL_CASUALTIES   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     3.609
Date:                Wed, 19 Jul 2023   Prob (F-statistic):             0.0271
Time:                        02:17:13   Log-Likelihood:                -7096.4
No. Observations:                5707   AIC:                         1.420e+04
Df Residuals:                    5704   BIC:                         1.422e+04
Df Model:                           2
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              0.6282      0.037     17.188      0.000       0.557       0.700
time_range_num    -0.0266      0.013     -2.108      0.035      -0.051      -0.002
dow_num            0.0080      0.005      1.473      0.141      -0.003       0.019
==============================================================================
Omnibus:                     7651.073   Durbin-Watson:                   1.900
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          6562892.453
Skew:                           7.044   Prob(JB):                         0.00
Kurtosis:                     168.532   Cond. No.                         17.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.